export const ADD_NAME_TO_STATE = "ADD_NAME_TO_STATE";
export const GET_FEEDBACK_TYPE = "GET_FEEDBACK_TYPE";
export const ADD_FEEDBACK_EMPLOYEE = "ADD_FEEDBACK_EMPLOYEE";
export const FETCH_FEEDBACK = "FETCH_FEEDBACK";
